name: "Add New Module"
description: "Use this form to add a new module."
title: "[Add] Module: {{ name }}"
labels: ["module", "add"]
body:
  - type: dropdown
    id: category
    attributes:
      label: "Category"
      description: "Select the appropriate category for this module."
      options:
        - "Development / Core MagicMirror²"
        - "Education"
        - "Entertainment / Misc"
        - "Finance"
        - "Health"
        - "News / Information"
        - "Outdated Modules"
        - "Religion"
        - "Sports"
        - "Transport / Travel"
        - "Utility / IoT / 3rd Party / Integration"
        - "Voice Control"
        - "Weather"
  - type: input
    id: url
    attributes:
      label: "URL"
      description: "Provide the URL to the module's repository."
      placeholder: "https://github.com/username/repository"
    validations:
      required: true
  - type: input
    id: maintainer
    attributes:
      label: "Maintainer"
      description: "Name of the maintainer or organization."
    validations:
      required: true
  - type: input
    id: maintainer_url
    attributes:
      label: "Maintainer URL"
      description: "URL of the maintainer's GitHub, GitLab, Bitbucket, or other profile. No personal websites."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a brief description of the module's purpose."
    validations:
      required: true                                                                                                                                
